AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Replicate Data Between Accounts

Parameters:

  HandlerParameter:
    Type: String
    Description: Name de Handler this function

  FunctionName:
    Type: String
    Description: Name this function.

  Runtime:
    Type: String
    Description: Version this java running in function

  Timeout:
    Type: String
    Description: Time for timeout in seconds

  MemorySize:
    Type: Number
    Description: Size the memory for function

  SecGroup:
    Type: String

  Versao:
    Type: String

  Product:
    Type: String
    Default: "dynamodb-stream-sender"

  AccountReplica:
    Type: String
  
  RegionReplica:
    Type: String
  
  Env:
    Type: String

Resources:
  dynamoDBReplicaData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: !Ref HandlerParameter
      FunctionName: !Ref FunctionName
      Runtime: !Ref Runtime
      Timeout: !Ref Timeout
      MemorySize: !Ref MemorySize
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: ../../.serverless/dynamodb-stream-sender.zip

      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !ImportValue vpc-subnetPrvA
      Environment:
        Variables:
          REGION_REPLICA: !Ref RegionReplica
          ACCOUNT_REPLICA: !Ref AccountReplica
          FIFO_QUEUE_NAME: !Join [ "/", [!Sub "https://sqs.${AWS::Region}.amazonaws.com", !Sub "${AWS::AccountId}", "queueReplicaDataResilience.fifo"]]
                    
      Tags:
        env : !Ref Env
        service : !Ref Product
        stack : !Sub ${AWS::StackName}
        squad : squad-cloud
        slack : squad-cloud
        email : cloud
        resource : lambda

  replicaDataManagerRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - 
            Effect: Allow
            Principal:
              AWS:
              - !Sub arn:aws:iam::${AccountReplica}:root
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      RoleName: ReplicaDataManagerRole

Outputs:
  
  dynamoDBReplicaData:
    Description: Export to Arn AWS Lambda dynamoDBReplicaData
    Value: !GetAtt dynamoDBReplicaData.Arn
    Export:
      Name: dynamoDBReplicaData
